#!perl
use Cassandane::Tiny;

sub test_touch_raclmodseq ($self)
{

    my $admintalk = $self->{adminstore}->get_client();
    my $imaptalk = $self->{store}->get_client();

    my $precounters = $self->{store}->get_counters();

    $admintalk->_imap_cmd('Raclmodseq', '', 0, 'cassandane');
    $self->assert_str_equals('ok',
        $admintalk->get_last_completion_response());

    my $postcounters = $self->{store}->get_counters();
    $self->assert_num_not_equals($precounters->{raclmodseq}, $postcounters->{raclmodseq}, "RACL modseq changed");
}
