#!perl
use Cassandane::Tiny;

sub test_maxargssize_fetch_headers
{
    my ($self) = @_;

    $self->assert_cmd_bye_toobig('FETCH', '1',
                                 [ 'BODY[HEADER.FIELDS', [ "X" x 25, "X" x 25 ] ] );
}
