#!perl
use Cassandane::Tiny;

sub test_maxargssize_status ($self)
{
    $self->assert_cmd_bye_toobig('STATUS', 'INBOX',
                                 [ 'MESSAGES', 'UIDNEXT',
                                   'UIDVALIDITY', 'UNSEEN', 'SIZE' ] );
}
