#!perl
use Cassandane::Tiny;

sub test_maxargssize_multisearch
{
    my ($self) = @_;

    $self->assert_cmd_bye_toobig('ESEARCH',
                                 'IN', [ 'MAILBOXES', [ "X" x 25, "X" x 25 ] ]);
}
