#!perl
use Cassandane::Tiny;

sub test_maxmessagesize_nosync_literal
{
    my ($self) = @_;

    my $talk = $self->{store}->get_client();
    # Do this by brute force until we have IMAPTalk v4.06+
    $talk->_imap_socket_out($talk->{CmdId}++ . " APPEND INBOX {101+}\015\012");
    $self->assert_no_toobig($talk);
    $self->assert_bye_toobig();
}
