.\" -*- nroff -*-
.TH COLLECTNEWS 8
.\" Copyright 1996, Carnegie Mellon University.  All Rights Reserved.
.\" 
.\" This software is made available for academic and research
.\" purposes only.  No commercial license is hereby granted.
.\" Copying and other reproduction is authorized only for research,
.\" education, and other non-commercial purposes.  No warranties,
.\" either expressed or implied, are made regarding the operation,
.\" use, or results of the software.  Such a release does not permit
.\" use of the code for commercial purposes or benefits by anyone
.\" without specific, additional permission by the owner of the code.
.SH NAME
collectnews \- add news articles to Cyrus header files
.SH SYNOPSIS
.B collectnews
.SH DESCRIPTION
.I Collectnews
reads article data from the standard input.
It uses this information to update the files necessary for reading
the articles through the Cyrus IMAP server.
.I Collectnews
is designed to be used by InterNetNews to update the IMAP database as
the articles come in.
.PP
The input is processed as an INN overview stream written as a ``WO''
entry in the
.IR newsfeeds (5)
file.  This data consists of lines of text.  Any tab 
and any data followed by a tab in an input line is ignored.  The
remaining text is a list of relative article pathnames, with a single
space between entries.
.PP
.I Collectnews
reads its configuration options out of the
.IR imapd.conf (5)
file.  The optional
.I newsprefix
option specifies a prefix to be prepended to newsgroup names to make
the corresponding IMAP mailbox names.
The required
.I partition-news
option specifies the pathname prefix to the IMAP news mailboxes.  The
value of
.I partition-news
concatenated with the dots-to-slashes-converted value of
.I newsprefix
must be the pathname of the news spool directory.
.SH FILES
.TP
.B /etc/imapd.conf
