.\" -*- nroff -*-
.TH POP3D 8
.\" Copyright 1999 Carnegie Mellon University
.\" 
.\" No warranties, either expressed or implied, are made regarding the
.\" operation, use, or results of the software.
.\"
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation is hereby granted for non-commercial purposes only
.\" provided that this copyright notice appears in all copies and in
.\" supporting documentation.
.\"
.\" Permission is also granted to Internet Service Providers and others
.\" entities to use the software for internal purposes.
.\"
.\" The distribution, modification or sale of a product which uses or is
.\" based on the software, in whole or in part, for commercial purposes or
.\" benefits requires specific, additional permission from:
.\"
.\"  Office of Technology Transfer
.\"  Carnegie Mellon University
.\"  5000 Forbes Avenue
.\"  Pittsburgh, PA  15213-3890
.\"  (412) 268-4387, fax: (412) 268-7395
.\"  tech-transfer@andrew.cmu.edu
.SH NAME
imtest \- utility to authenticate to imapd
.SH SYNOPSIS
.B imtest
.SH DESCRIPTION
.I imtest
is a utility that allows you to authenticate to the IMAP or IMSP
server and issue commands to it. Once authenticated you may issue any
IMAP or IMSP command by simply typing it in. Encryption layers are
handled for you as well as all the headache of authenticating. This
utility is often used for testing the operation of a imsp or imap
server. Also those developing IMAP clients find it useful.


.PP
.SH OPTIONS

.I -p <port>
Port to connect to. If left off this defaults to "imap" as defined in
/etc/services. This takes numerical or named arguements

.I -m <mechanism>
Force installsieve to use <mechanism> for authentication. If not
specified the strongest authentication mechanism is chosen.

.I -u <user>
Userid/Authname to use for authentication.

.I -l <num>
Maximum protection layer to use (0=none; 1=integrity; etc). For
example if you are using the KERBEROS_V4 authentication mechanism
specifing 0 will force imtest to not use any layer and specifying 1
will force it to use the integrity layer. By default the KERBEROS_V4
protection layer will be used if the server supports it.

.I -r realm
Specify the realm to use. Certain authentication mechanisms
(e.g. DIGEST-MD5) require one to specify the realm

.I -f <file>
Pipe file into connection after authentication

.I -v
Verbose. Print out more information than usual

.I -z
Timing test.

.TP
