.\" -*- nroff -*-
.TH KRB.EQUIV 5
.\" Copyright 1996, Carnegie Mellon University.  All Rights Reserved.
.\" 
.\" This software is made available for academic and research
.\" purposes only.  No commercial license is hereby granted.
.\" Copying and other reproduction is authorized only for research,
.\" education, and other non-commercial purposes.  No warranties,
.\" either expressed or implied, are made regarding the operation,
.\" use, or results of the software.  Such a release does not permit
.\" use of the code for commercial purposes or benefits by anyone
.\" without specific, additional permission by the owner of the code.
.SH NAME
\fB/etc/krb.equiv\fR \- Kerberos equivalences
.SH DESCRIPTION
.I krb.equiv
contains zero or more lines, each of which describes a mapping of a kerberos
principal (\fIuserid@host\fR) to a local user (\fIuserid\fR or alias).  
Each line of the file consists of two fields,
separated by at least one whitespace character; other blanks are
ignored.  The first field is the kerberos principal name to
remap, and the second is the name of the corresponding local user.
.SH SAMPLE FILE
.PP
.nf
tyq4@ANDY.CMU.EDU tyq4
tyq4@DEANNA.ORG tyq4
ty347@ECE.CMU.EDU tyq4
jj12@ANDY.CMU.EDU tick
tick@DEANNA.ORG tick
jy9o@ANDY.CMU.EDU jyager
jyager@CS.CMU.EDU jyager

