.\" -*- nroff -*-
.TH KRB.EQUIV 5
.\" 	(C) Copyright 1994 by Carnegie Mellon University
.\" 
.\"                      All Rights Reserved
.\" 
.\" Permission to use, copy, modify, distribute, and sell this software
.\" and its documentation for any purpose is hereby granted without
.\" fee, provided that the above copyright notice appear in all copies
.\" and that both that copyright notice and this permission notice
.\" appear in supporting documentation, and that the name of Carnegie
.\" Mellon University not be used in advertising or publicity
.\" pertaining to distribution of the software without specific,
.\" written prior permission.  Carnegie Mellon University makes no
.\" representations about the suitability of this software for any
.\" purpose.  It is provided "as is" without express or implied
.\" warranty.
.\"
.\" CARNEGIE MELLON UNIVERSITY DISCLAIMS ALL WARRANTIES WITH REGARD TO
.\" THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS, IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE
.\" FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
.\" AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
.\" OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
.\" SOFTWARE.
.SH NAME
\fB/etc/krb.equiv\fR \- Kerberos equivalences
.SH DESCRIPTION
.I krb.equiv
contains zero or more lines, each of which describes a mapping of a kerberos
principal (\fIuserid@host\fR) to a local user (\fIuserid\fR or alias).  
Each line of the file consists of two fields,
separated by at least one whitespace character; other blanks are
ignored.  The first field is the kerberos principal name to
remap, and the second is the name of the corresponding local user.
.SH SAMPLE FILE
.PP
.nf
tyq4@ANDY.CMU.EDU tyq4
tyq4@DEANNA.ORG tyq4
ty347@ECE.CMU.EDU tyq4
jj12@ANDY.CMU.EDU tick
tick@DEANNA.ORG tick
jy9o@ANDY.CMU.EDU jyager
jyager@CS.CMU.EDU jyager

