.\" -*- nroff -*-
.TH MASTER 8 "Project Cyrus" CMU
.\" 
.\" Copyright (c) 1996-2000 Carnegie Mellon University.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer. 
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\"
.\" 3. The name "Carnegie Mellon University" must not be used to
.\"    endorse or promote products derived from this software without
.\"    prior written permission. For permission or any other legal
.\"    details, please contact  
.\"      Office of Technology Transfer
.\"      Carnegie Mellon University
.\"      5000 Forbes Avenue
.\"      Pittsburgh, PA  15213-3890
.\"      (412) 268-4387, fax: (412) 268-7395
.\"      tech-transfer@andrew.cmu.edu
.\"
.\" 4. Redistributions of any form whatsoever must retain the following
.\"    acknowledgment:
.\"    "This product includes software developed by Computing Services
.\"     at Carnegie Mellon University (http://www.cmu.edu/computing/)."
.\"
.\" CARNEGIE MELLON UNIVERSITY DISCLAIMS ALL WARRANTIES WITH REGARD TO
.\" THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS, IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE
.\" FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
.\" AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
.\" OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\" 
.\" $Id: master.8,v 1.8 2002/12/10 15:49:10 rjs3 Exp $
.SH NAME
master \- master Cyrus process
.SH SYNOPSIS
.B master
[
.B \-l
.I listen queue
]
[
.B \-p
.I pidfile
]
.B \-d
[
.B \-D
]
.SH DESCRIPTION
.I Master
is the process that controls all of the Cyrus processes. This process
is responsible for creating all imapd, pop3d, lmtpd and sieved child
processes. This process also initializes the Berkeley DB code and
performs scheduled cleanup/maintenance.
.PP
If this process dies, then no new sessions will be started.
.PP
It kills itself and all child processes
when it receives a SIGTERM.
.SH OPTIONS
.TP
.BI \-l " listen queue backlog"
Increase the listen queue backlog. By default, the listen queue is set
to 32.   On systems with a high connection rate, it may be desirable
to increase this value. refer to \fBlisten(2)\fR for details.
.TP
.BI \-p " pidfile"
Use
.I pidfile
as the pidfile.  If not specified, defaults to /var/run/cyrus-master.pid
.TP
.BI \-d
Start in daemon mode (run in background and disconnect from controlling
terminal).
.TP
.BI \-D
Don't close stdin/stdout/stderr. Primiarly useful for debugging.
.SH CONFIGURATION
Upon execution,
.I master
reads its configuration information out of the
.IR cyrus.conf (5)
file.
.PP
.I Master
rereads its configuration file when it receives a hangup signal,
SIGHUP.  Services and events may be added, deleted or modified when the
configuration file is reread.  Any active services removed from the
configuration file will be allowed to run until completion.
.SH NOTES
The environment variable \fBCYRUS_VERBOSE\fR can be set to log additional
debugging information. Setting the value to 1 results in base level logging. 
Setting it higher results in more log messages being generated.
.SH FILES
.TP
.B /etc/cyrus.conf, /etc/imapd.conf, /var/run/cyrus-master.pid
.SH SEE ALSO
.PP
\fBcyrus.conf(5)\fR, \fBimapd.conf(5)\fR, \fBimapd(8)\fR,
\fBpop3d(8)\fR, \fBlmtpd(8)\fR, \fBtimsieved(8)\fR, \fBidled(8)\fR
