#!perl
use Cassandane::Tiny;

sub test_participantidentity_set
    :min_version_3_3
    ($self)
{
    my $jmap = $self->default_user->jmap;
    my $default_cal_id = $self->default_user->calendars->default->id;

    my $res = $jmap->CallMethods([
        ['ParticipantIdentity/set', {
            create => {
                partid1 => {
                    sendTo => {
                        imip => 'mailto:foo@local',
                    },
                },
            },
            update => {
                partid2 => {
                    name => 'bar',
                },
            },
            destroy => ['partid3'],
        }, 'R1']
    ]);

    $self->assert_str_equals('forbidden',
        $res->[0][1]{notCreated}{partid1}{type});
    $self->assert_str_equals('forbidden',
        $res->[0][1]{notUpdated}{partid2}{type});
    $self->assert_str_equals('forbidden',
        $res->[0][1]{notDestroyed}{partid3}{type});
}
