((c-mode  .  ((indent-tabs-mode . nil)
              (c-basic-offset . 4)
              (tab-width . 4)))
 (c++-mode . ((indent-tabs-mode . nil)
              (c-basic-offset . 4)
              (tab-width . 4)))
 (js-mode .  ((require-final-newline . nil)
              (indent-tabs-mode . nil)
              (c-basic-offset . 4)
              (tab-width . 4)))
)
