#!perl
use Cassandane::Tiny;

require HTTP::Request;

sub test_cors_preflight
    :HttpAllowCorsFooExampleCom
    ($self)
{
    my $jmap = $self->{jmap};
    my $http = $self->{instance}->get_service("http");

    my $req = HTTP::Request->new(
        OPTIONS => "" . $jmap->api_uri,
        [
            'Origin' => 'https://foo.example.com',
            'Access-Control-Request-Method' => 'POST',
        ],
    );
    my $res = $jmap->http_request($req);
    $self->assert_str_equals('200', $res->code);
    $self->assert_str_equals('https://foo.example.com',
        $res->header('access-control-allow-origin'));
}
