#!perl
use Cassandane::Tiny;

sub test_eventsource_disabled
    :JMAPExtensions :NoAltNameSpace :NoStartInstances
    ($self)
{
    $self->{instance}->{config}->set('jmap_pushpoll' => 0);
    $self->_start_instances();
    $self->_setup_http_service_objects();

    my $jmap = $self->{jmap};
    my $http = $self->{instance}->get_service("http");
    my $session = $jmap->get_client_session->client_session;
    $self->assert_not_null($session);
    $self->assert_null($session->{eventSourceUrl});

    my $uri = $jmap->api_uri . "eventsource/";

    my $es_request = HTTP::Request->new(
        GET => $uri,
        [
            $jmap->_maybe_auth_header,
            'Last-Event-Id' => '0',
        ],
    );

    my $http_res = $jmap->http_request($es_request);
    $self->assert_str_equals('404', $http_res->code);
}
