/* This file was generated by mib2c and is intended for use as a mib module
  for the ucd-snmp snmpd agent. */


#ifndef _MIBGROUP_CYRUSMASTERMIB_H
#define _MIBGROUP_CYRUSMASTERMIB_H


/* we may use header_generic and header_simple_table from the util_funcs module */


config_require(util_funcs)


/* function prototypes */


void   init_cyrusMasterMIB(void);
FindVarMethod var_cyrusMasterMIB;
FindVarMethod var_serviceTable;





#endif /* _MIBGROUP_CYRUSMASTERMIB_H */
