#!perl
use Cassandane::Tiny;

sub test_pushsubs
    :needs_component_jmap
{
    my ($self) = @_;

    my $jmap = $self->{jmap};
    my $CardDAV = $self->{carddav};

    xlog "create subscription";
    my $res = $jmap->CallMethods([
        ['PushSubscription/set', {
            create => {
                "1" => {
                    deviceClientId => "a889-ffea-910",
                    url => "https://example.com/push/?device=X8980fc&client=12c6d086",
                    types => [ "Mailbox", "Email" ]
                },
            },
         }, "R1"]
    ]);
    my $id = $res->[0][1]{created}{"1"}{id};
    $self->assert_not_null($id);

    $res = $CardDAV->Request('GET', '/dblookup/pushsubs', '',
        User => 'cassandane'
    );

    my $json = eval { decode_json($res->{content}) };
    my $code = $json->[0]{verificationCode};

    $self->assert_str_equals($id, $json->[0]{id});
    $self->assert_equals(JSON::false, $json->[0]{isVerified});
    $self->assert_not_null($json->[0]{url});
    $self->assert_not_null($code);

    xlog "verify subscription";
    $res = $jmap->CallMethods([
        ['PushSubscription/set', {
            update => {
                $id => {
                    verificationCode => $code
                },
            },
         }, "R1"]
    ]);

    $self->assert(exists $res->[0][1]{updated}{$id});

    $res = $CardDAV->Request('GET', '/dblookup/pushsubs', '',
        User => 'cassandane'
    );

    $json = eval { decode_json($res->{content}) };

    $self->assert_str_equals($id, $json->[0]{id});
    $self->assert_equals(JSON::true, $json->[0]{isVerified});
}
