#!perl
use Cassandane::Tiny;

sub test_card_get_no_type_vcardparams
    ($self)
{
    my $carddav = $self->default_user->carddav;
    my $jmap = $self->default_user->jmap;

    xlog $self, "Create vCard with unknown TYPE parameter value";
    my $vcard = <<~"EOF";
    BEGIN:VCARD
    VERSION:3.0
    UID:EE433ED1-C99B-434C-8B67-716907A1E9BA
    N:Test;;;;
    FN:Test
    EMAIL;TYPE=INTERNET:user\@example.com
    END:VCARD
    EOF
    $vcard =~ s/\r?\n/\r\n/gs;
    $carddav->Request('PUT', 'Default/test.vcf', $vcard, 'Content-Type' => 'text/vcard');

    xlog $self, "Assert no vCardParams is set in the EmailAddress object";
    my $jcard = $jmap->request([
        [ 'ContactCard/get', { properties => ['emails'], } ]]
    )->single_sentence('ContactCard/get')->arguments->{list}[0];
    $self->assert_cmp_deeply(hashbag(
        ignore() => { address => 'user@example.com' }
    ), $jcard->{emails});
}
