#!perl
use Cassandane::Tiny;

sub test_contact_get_with_addressbookid
    :min_version_3_1
    ($self)
{
    my $jmap = $self->{jmap};

    xlog $self, "get contact with addressbookid";
    my $res = $jmap->CallMethods([['Contact/get',
                                   { addressbookId => "Default" }, "R3"]]);
    $self->assert_num_equals(0, scalar @{$res->[0][1]{list}});
}
