#!perl
use Cassandane::Tiny;

sub test_subscribe_vd
    :VirtDomains :CrossDomains
{
    my ($self) = @_;

    $self->shared_subscribe_common('firstuser@example.com',
                                   'seconduser@example.com');
}
