#!perl
use Cassandane::Tiny;

sub test_basic_abortedidled
    :needs_component_idled
{
    my ($self) = @_;

    xlog $self, "Basic test of the IDLE command, idled started but aborted";

    $self->{instance}->{config}->set(imapidlepoll => '2');
    $self->{instance}->start();
    $self->start_and_abort_idled();

    $self->common_basic();
}
