#!perl
use Cassandane::Tiny;

sub test_delivery_noidled ($self)
{
    xlog $self, "Test the IDLE command vs local delivery, no idled started";

    $self->{instance}->{config}->set(imapidlepoll => '2');
    $self->{instance}->start();
    $self->common_delivery();
}
