#!perl
use Cassandane::Tiny;

sub test_shutdownfile_abortedidled
    :needs_component_idled
{
    my ($self) = @_;

    xlog $self, "Test the IDLE command vs the shutdownfile, idled started but aborted";

    $self->{instance}->{config}->set(imapidlepoll => '2');
    $self->{instance}->start();
    $self->start_and_abort_idled();

    $self->common_shutdownfile();
}
