.\" -*- nroff -*-
.TH RECONSTRUCT 8
.\" Copyright 1996, Carnegie Mellon University.  All Rights Reserved.
.\" 
.\" This software is made available for academic and research
.\" purposes only.  No commercial license is hereby granted.
.\" Copying and other reproduction is authorized only for research,
.\" education, and other non-commercial purposes.  No warranties,
.\" either expressed or implied, are made regarding the operation,
.\" use, or results of the software.  Such a release does not permit
.\" use of the code for commercial purposes or benefits by anyone
.\" without specific, additional permission by the owner of the code.
.SH NAME
arbitron \- arbitron mailboxes
.SH SYNOPSIS
.B arbitron
[
.B \-d
days
] [
.B \-p
months
]
.IR mailbox ...
.SH DESCRIPTION
.I Arbitron
collects and reports readership statistics for mailboxes on the
server.  It also optionally prunes the mailboxes of \\Seen state for
dormant users.
.PP
.I Arbitron
produces one line of output per mailbox, reporting the number of
readers followed by a space and the name of the mailbox.
\fBIMPORTANT: This format is subject to change in future versions.\fR
.PP
Each "reader" is a distinct authentication identity which has
"s" rights to the mailbox and which has SELECTed the mailbox within
the past
.I days
days.
Users are not counted as reading their own personal mailboxes.
Personal mailboxes are not reported unless there is at least one
reader other than the mailboxes owner.
.SH OPTIONS
.TP
.BI "\-d " days
Count as a reader an authentication identity which has SELECTed the
mailbox within
.I days
days.  Default is 30.
.TP
.BI "\-p " months
Prune \\Seen state for users who have not SELECTed the mailbox within
.I months
months.  Default is infinity.
.SH FILES
.TP
.B /etc/imapd.conf
