.\" -*- nroff -*-
.TH RECONSTRUCT 8
.\" Copyright 1998 Carnegie Mellon University
.\" 
.\" No warranties, either expressed or implied, are made regarding the
.\" operation, use, or results of the software.
.\"
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation is hereby granted for non-commercial purposes only
.\" provided that this copyright notice appears in all copies and in
.\" supporting documentation.
.\"
.\" Permission is also granted to Internet Service Providers and others
.\" entities to use the software for internal purposes.
.\"
.\" The distribution, modification or sale of a product which uses or is
.\" based on the software, in whole or in part, for commercial purposes or
.\" benefits requires specific, additional permission from:
.\"
.\"  Office of Technology Transfer
.\"  Carnegie Mellon University
.\"  5000 Forbes Avenue
.\"  Pittsburgh, PA  15213-3890
.\"  (412) 268-4387, fax: (412) 268-7395
.\"  tech-transfer@andrew.cmu.edu
.SH NAME
arbitron \- arbitron mailboxes
.SH SYNOPSIS
.B arbitron
[
.B \-d
days
] [
.B \-p
months
]
.IR mailbox ...
.SH DESCRIPTION
.I Arbitron
collects and reports readership statistics for mailboxes on the
server.  It also optionally prunes the mailboxes of \\Seen state for
dormant users.
.PP
.I Arbitron
produces one line of output per mailbox, reporting the number of
readers followed by a space and the name of the mailbox.
\fBIMPORTANT: This format is subject to change in future versions.\fR
.PP
Each "reader" is a distinct authentication identity which has
"s" rights to the mailbox and which has SELECTed the mailbox within
the past
.I days
days.
Users are not counted as reading their own personal mailboxes.
Personal mailboxes are not reported unless there is at least one
reader other than the mailboxes owner.
.SH OPTIONS
.TP
.BI "\-d " days
Count as a reader an authentication identity which has SELECTed the
mailbox within
.I days
days.  Default is 30.
.TP
.BI "\-p " months
Prune \\Seen state for users who have not SELECTed the mailbox within
.I months
months.  Default is infinity.
.SH FILES
.TP
.B /etc/imapd.conf
