.\" -*- nroff -*-
.TH COLLECTNEWS 8
.\" 	(C) Copyright 1994 by Carnegie Mellon University
.\" 
.\"                      All Rights Reserved
.\" 
.\" Permission to use, copy, modify, distribute, and sell this software
.\" and its documentation for any purpose is hereby granted without
.\" fee, provided that the above copyright notice appear in all copies
.\" and that both that copyright notice and this permission notice
.\" appear in supporting documentation, and that the name of Carnegie
.\" Mellon University not be used in advertising or publicity
.\" pertaining to distribution of the software without specific,
.\" written prior permission.  Carnegie Mellon University makes no
.\" representations about the suitability of this software for any
.\" purpose.  It is provided "as is" without express or implied
.\" warranty.
.\"
.\" CARNEGIE MELLON UNIVERSITY DISCLAIMS ALL WARRANTIES WITH REGARD TO
.\" THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS, IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE
.\" FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
.\" AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
.\" OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
.\" SOFTWARE.
.SH NAME
collectnews \- add news articles to Cyrus header files
.SH SYNOPSIS
.B collectnews
.SH DESCRIPTION
.I Collectnews
reads article data from the standard input.
It uses this information to update the files necessary for reading
the articles through the Cyrus IMAP server.
.I Collectnews
is designed to be used by InterNetNews to update the IMAP database as
the articles come in.
.PP
The input is processed as an INN overview stream written as a ``WO''
entry in the
.IR newsfeeds (5)
file.  This data consists of lines of text.  Any tab 
and any data followed by a tab in an input line is ignored.  The
remaining text is a list of relative article pathnames, with a single
space between entries.
.PP
.I Collectnews
reads its configuration options out of the
.IR imapd.conf (5)
file.  The optional
.I newsprefix
option specifies a prefix to be prepended to newsgroup names to make
the corresponding IMAP mailbox names.
The required
.I partition-news
option specifies the pathname prefix to the IMAP news mailboxes.  The
value of
.I partition-news
concatenated with the dots-to-slashes-converted value of
.I newsprefix
must be the pathname of the news spool directory.
.SH FILES
.TP
.B /etc/imapd.conf
