.\" -*- nroff -*-
.TH CTL_MBOXLIST 8
.\" 
.\" Copyright (c) 1998-2000 Carnegie Mellon University.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer. 
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\"
.\" 3. The name "Carnegie Mellon University" must not be used to
.\"    endorse or promote products derived from this software without
.\"    prior written permission. For permission or any other legal
.\"    details, please contact  
.\"      Office of Technology Transfer
.\"      Carnegie Mellon University
.\"      5000 Forbes Avenue
.\"      Pittsburgh, PA  15213-3890
.\"      (412) 268-4387, fax: (412) 268-7395
.\"      tech-transfer@andrew.cmu.edu
.\"
.\" 4. Redistributions of any form whatsoever must retain the following
.\"    acknowledgment:
.\"    "This product includes software developed by Computing Services
.\"     at Carnegie Mellon University (http://www.cmu.edu/computing/)."
.\"
.\" CARNEGIE MELLON UNIVERSITY DISCLAIMS ALL WARRANTIES WITH REGARD TO
.\" THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS, IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE
.\" FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
.\" AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
.\" OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\" 
.\" $Id: ctl_mboxlist.8,v 1.7.2.1 2003/02/27 18:12:33 rjs3 Exp $
.SH NAME
ctl_mboxlist \- perform operations on the mailbox list database
.SH SYNOPSIS
.B ctl_mboxlist
[
.B \-C
.I config-file
]
.B \-d
[
.B \-x
]
[
\fB\-p \fIpartition\fR
]
[
\fB\-f \fIfilename\fR
]
.br
.B ctl_mboxlist
[
.B \-C
.I config-file
]
.B \-u
[
\fB\-f \fIfilename\fR
]
.br
.B ctl_mboxlist
[
.B \-C
.I config-file
]
.B \-m
[
\fB\-a \fR
]
[
\fB\-w \fR
]
.br
             [
\fB\-f \fIfilename\fR
]
.SH DESCRIPTION
.I Ctl_mboxlist
is used to perform various administrative operations on the mailbox
list database.
.PP
.I Ctl_mboxlist
reads its configuration options out of the
.IR imapd.conf (5)
file unless specified otherwise by \fB-C\fR.
The
.I configdirectory
option is used to determine the default location of the mailbox list database.
.SH OPTIONS
.TP
.BI \-C\  "config-file"
Read configuration options from \fIconfig-file\fR.
.TP
.B \-d
Dump the contents of the database to standard output in a portable
flat-text format.
.TP
.B \-x
When performing a dump, remove the mailboxes dumped from the mailbox list
(mostly useful when specified with -p)
.TP
.BI \-p\  "partition"
When performing a dump, dump only thise mailboxes that live on \fIpartition\fR
.TP
.B \-u
Load the contents of the database from standard input.  The input MUST
be in the format output using the \fB\-d\fR option.
.TP
.B \-m
For backend servers in the Cyrus Murder, synchronize the local mailbox list
file with the MUPDATE server.
.TP
.B \-a
When used with -m, assume the local mailboxes file is authoritiative, 
that is, only change the mupdate server, do not delete any local mailboxes.
USE THIS OPTION WITH CARE, as it allows namespace collisions into the murder.
.TP
.B \-w
When used with -m, print out what would be done but do not perform the
operations.
.TP
\fB\-f \fIfilename\fR
Use the database specified by \fIfilename\fR instead of the default
(\fIconfigdirectory\fB/mailboxes.db\fR).
.SH FILES
.TP
.B /etc/imapd.conf
.SH SEE ALSO
.PP
\fBimapd.conf(5)\fR, \fBmaster(8)\fR
