.\" -*- nroff -*-
.TH FUD 8
.\" Copyright 1998 Carnegie Mellon University
.\" 
.\" No warranties, either expressed or implied, are made regarding the
.\" operation, use, or results of the software.
.\"
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation is hereby granted for non-commercial purposes only
.\" provided that this copyright notice appears in all copies and in
.\" supporting documentation.
.\"
.\" Permission is also granted to Internet Service Providers and others
.\" entities to use the software for internal purposes.
.\"
.\" The distribution, modification or sale of a product which uses or is
.\" based on the software, in whole or in part, for commercial purposes or
.\" benefits requires specific, additional permission from:
.\"
.\"  Office of Technology Transfer
.\"  Carnegie Mellon University
.\"  5000 Forbes Avenue
.\"  Pittsburgh, PA  15213-3890
.\"  (412) 268-4387, fax: (412) 268-7395
.\"  tech-transfer@andrew.cmu.edu
.SH NAME
fud \- provide information about user mailboxes
.SH SYNOPSIS
.B fud
.SH DESCRIPTION
.I FUD
is a long lived datagram daemon started from inetd that provides information about when a user last
read their mail, when mail last arrived in a user's mailbox, and how
many messages are recent for that user.
.SH FILES
.TP
.B /etc/imapd.conf
.SH BUGS
Though not really a bug, 
.B FUD
will silently ignore any requests that it does not consider valid.
.PP
.B FUD
is an experimental interface meant to provide information to build a
finger-like service around.  Eventually it should be superceded by LDAP
or ACAP (using the mailbox dataset).
