.\" -*- nroff -*-
.TH IMAPD.CONF 5 "Project Cyrus" CMU
.\" Copyright 1998 Carnegie Mellon University
.\" 
.\" No warranties, either expressed or implied, are made regarding the
.\" operation, use, or results of the software.
.\"
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation is hereby granted for non-commercial purposes only
.\" provided that this copyright notice appears in all copies and in
.\" supporting documentation.
.\"
.\" Permission is also granted to Internet Service Providers and others
.\" entities to use the software for internal purposes.
.\"
.\" The distribution, modification or sale of a product which uses or is
.\" based on the software, in whole or in part, for commercial purposes or
.\" benefits requires specific, additional permission from:
.\"
.\"  Office of Technology Transfer
.\"  Carnegie Mellon University
.\"  5000 Forbes Avenue
.\"  Pittsburgh, PA  15213-3890
.\"  (412) 268-4387, fax: (412) 268-7395
.\"  tech-transfer@andrew.cmu.edu
.SH NAME
imapd.conf \- IMAP configuration file
.SH DESCRIPTION
\fB/etc/imapd.conf\fR 
is the configuration file for the Cyrus IMAP server.  It defines
local parameters for IMAP. 
.PP
Each line of the \fB/etc/imapd.conf\fR file has the form
.IP
\fIoption\fR: \fIvalue\fR
.PP
where \fIoption\fR is the name of the configuration option being set
and \fIvalue\fR is the value that the configuration option is being
set to.
.PP
Blank lines and lines beginning with ``#'' are ignored.
.PP
For boolean options, the values ``yes'', ``on'', ``t'', and ``1'' turn the
option on, the values ``no'', ``off'', ``f'', and ``0'' turn the option off.
.SH FIELD DESCRIPTIONS
.PP
The sections below detail options that can be placed in the
\fB/etc/imapd.conf\fR file, and show each option's default value.
Some options have no default value, these are listed with
``<no default>''.  Some options default to the empty string, these
are listed with ``<none>''.
.IP "\fBconfigdirectory:\fR <no default>" 5
The pathname of the IMAP configuration directory.  This field is required.
.IP "\fBdefaultpartition:\fR default" 5
The partition name used by default for new mailboxes.
.IP "\fBpartition-\fIname\fB:\fR <no default>" 5
The pathname of the partition \fIname\fR.  At least one field, for the
partition named in the \fBdefaultpartition\fR option, is required.
For example, if the value of the \fBdefaultpartion\fR option is
\fBdefault\fR, then the \fBpartition-default\fR field is required.
.IP "\fBumask:\fR 077" 5
The umask value used by various Cyrus IMAP programs.
.IP "\fBallowanonymouslogin:\fR no" 5
Permit logins by the user "anonymous" using any password.  Also allows
use of the SASL ANONYMOUS mechanism.
.IP "\fBquotawarn:\fR 90" 5
The percent of quota utilization over which the server generates
warnings.
.IP "\fBtimeout:\fR 30" 5
The length of the IMAP server's inactivity autologout timer,
in minutes.  The minimum value is 30, the default.
.IP "\fBimapidresponse:\fR yes" 5
If enabled, the server responds to an ID command with a parameter
list containing: version, vendor, support-url, os, os-version,
command, arguments, environment.  Otherwise the server returns NIL.
.IP "\fBpoptimeout:\fR 10" 5
Set the length of the POP server's inactivity autologout timer,
in minutes.  The minimum value is 10, the default.
.IP "\fBpopminpoll:\fR 0" 5
Set the minimum amount of time the server forces users to wait between
successive POP logins,
in minutes.  The default is 0.
.IP "\fBpopexpiretime:\fR 0" 5
The number of days advertised as being the minimum a message may be left on
the POP server before it is deleted (via the CAPA command, defined in the POP3
Extension Mechanism, which some clients may support).  "NEVER", the default,
may be specified with a negative number.  The Cyrus POP3 server never deletes
mail, no matter what the value of this parameter is.  However, if a site
implements a less liberal policy, it needs to change this parameter
accordingly.
.IP "\fBadmins:\fR <none>" 5
The list of userids with administrative rights.  Separate each userid
with a space.  Sites using Kerberos authentication may use
separate "admin" instances.
.PP
Note that accounts used by users should not be administrators.  Administrative 
accounts should not receive mail.  That is, if user "jbRo" is a user reading
mail, he should not also be in the admins line.  Some problems may occur
otherwise, most notably  the ability of administrators to create top-level
mailboxes visible to users, but not writable by users.
.IP "\fBproxyservers:\fR <none>" 5
A list of users and groups that are allowed to proxy for other users,
seperated by spaces.  Any user listed in this will be allowed to login
for any other user: use with caution.
.IP "\fBdefaultacl:\fR anyone lrs" 5
The Access Control List (ACL) placed on a newly-created (non-user) 
mailbox that does not have a parent mailbox.
.IP "\fBnewsspool\fB:\fR <no default>" 5
The pathname of the news spool directory.  Only used if the
\fBpartition-news\fR configuration option is set.
.IP "\fBnewsprefix:\fR <none>" 5
Prefix to be prepended to newsgroup names to make the corresponding
IMAP mailbox names.
.IP "\fBautocreatequota:\fR 0" 5
If nonzero, normal users may create their own IMAP accounts by
creating the mailbox INBOX.  The user's quota is set to the value if
it is positive, otherwise the user has unlimited quota.
.IP "\fBlogtimestamps:\fR no" 5
Include notations in the protocol telemetry logs indicating the number of
seconds since the last command or response.
.IP "\fBplaintextloginpause:\fR 0" 5
Number of seconds to pause after a successful plaintext login.  For
systems that support strong authentication, this permits users to
perceive a cost of using plaintext passwords.  (This does not effect
the use of PLAIN in SASL authentications.)
.IP "\fBsrvtab:\fR /etc/srvtab" 5
The pathname of \fIsrvtab\fR file containing the server's private 
key.  This option is passed to the SASL library and overrides its
default setting.
.IP "\fBloginrealms:\fR <none>" 5
The list of remote realms whose users may log in using 
cross-realm authentications.  Seperate each realm name
by a space.  (A cross-realm identity is considered any identity
returned by SASL with an "@" in it.)
.IP "\fBloginuseacl:\fR no" 5
If enabled, any authentication identity which has \fBa\fR rights on a
user's INBOX may log in as that user.
.IP "\fBsingleinstancestore:\fR yes" 5
If enabled, deliver running in LMTP mode attempts to only write one
copy of a message per partition and create hard links, resulting in a
potentially large disk savings.
.IP "\fBreject8bit:\fR no" 5
If enabled, deliver rejects messages with 8-bit characters in the headers.
Otherwise, 8-bit characters are changed to `X'.  (A proper soultion to
non-ASCII characters in headers is offered by RFC 2047 and its predecessors.)
.IP "\fBnetscapeurl:\fR http://andrew2.andrew.cmu.edu/cyrus/imapd/netscape-admin.html" 5
If enabled at compile time, this specifies a URL to reply when Netscape
asks the server where the mail administration HTTP server is.  The default
is a site at CMU with a hopefully informative message; administrators
should set this to a local resource with some information of greater
use.
.IP "\fBsieveusehomedir:\fR false" 5
If enabled, deliver will look for Sieve scripts in user's home
directories: ~user/.sieve.
.IP "\fBsievedir:\fR /usr/sieve" 5
If sieveusehomedir is false, this directory is searched for Sieve
scripts.
.IP "\fBsendmail:\fR /usr/lib/sendmail" 5
The pathname of the sendmail executable.  Sieve uses sendmail for sending
rejections, redirects and vacation responses.
.IP "\fBpostmaster:\fR postmaster" 5
Username that is used as the 'From' address in rejection MDNs produced
by sieve.
.IP "\fBhashimapspool:\fR false" 5
If enabled, the partitions will also be hashed, in addition to the
hashing done on configuration directories.  This is recommended if one
partition has a very bushy mailbox tree.
.IP "\fBsieve_maxscriptsize:\fR 32" 5
Maximum size (in kilobytes) any sieve script can be, enforced at
submission by timsieved(8).
.IP "\fBsieve_maxscripts:\fR 5" 5
Maximum number of sieve scripts any user may have, enforced at
submission by timsieved(8).
.IP "\fBsasl_maximum_layer:\fR 256" 5
Maximum SSF (security strength factor) that the server will allow a
client to negotiate.
.IP "\fBsasl_minimum_layer:\fR 0" 5
The minimum SSF that the server will allow a client to negotiate.  A
value of 1 requires integrity protection; any higher value requires
some amount of encryption.
.IP "\fBsasl_pwcheck_method:\fR PAM" 5
The mechanism used by the server to verify plaintext passwords.
Possible values also include "kerberos_v4", "passwd", and "shadow".
.IP "\fBsasl_auto_transition:\fR no" 5
If enabled, the SASL library will automatically create authentication
secrets when given a plaintext password.  See the SASL documentation.
.IP "\fBsasl_option\fR" 5
Any other SASL option can be set by preceeding it with "sasl_".  This
file overrides the SASL configuration file.

.SH SEE ALSO
.PP
\fBimapd(8)\fR, \fBtimsieved(8)\fR, \fBdeliver(8)\fR
