.\" -*- nroff -*-
.TH INSTALLSIEVE 1 "Project Cyrus" CMU
.\" 
.\" Copyright (c) 1999-2000 Carnegie Mellon University.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer. 
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in
.\"    the documentation and/or other materials provided with the
.\"    distribution.
.\"
.\" 3. The name "Carnegie Mellon University" must not be used to
.\"    endorse or promote products derived from this software without
.\"    prior written permission. For permission or any other legal
.\"    details, please contact  
.\"      Office of Technology Transfer
.\"      Carnegie Mellon University
.\"      5000 Forbes Avenue
.\"      Pittsburgh, PA  15213-3890
.\"      (412) 268-4387, fax: (412) 268-7395
.\"      tech-transfer@andrew.cmu.edu
.\"
.\" 4. Redistributions of any form whatsoever must retain the following
.\"    acknowledgment:
.\"    "This product includes software developed by Computing Services
.\"     at Carnegie Mellon University (http://www.cmu.edu/computing/)."
.\"
.\" CARNEGIE MELLON UNIVERSITY DISCLAIMS ALL WARRANTIES WITH REGARD TO
.\" THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS, IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE
.\" FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
.\" AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
.\" OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\" 
.\" $Id: installsieve.1,v 1.5.4.1 2003/02/27 18:12:33 rjs3 Exp $
.SH NAME
installsieve \- user utility for managing sieve scripts
.SH SYNOPSIS
.B installsieve
.SH DESCRIPTION
.I installsieve
is a utility that allows users to manage their sieve scripts kept on
the server.

.PP
.SH OPTIONS

.I -v <name>
View script with the given name. The script if retrieved sucessfully
is output to standard output.

.I -l
List all of the scripts currently on the server. If one of the scripts
is active a arrow is printed indicating that it is the active script.

.I -p <port>
Port to connect to. If left off this defaults to "sieve" as defined in
/etc/services.

.I -i <file>
Install a file onto the server. If a script with the same name already
exists on the server it is overwritten. Upon sucessfully putting the
script on the server the script is set active. If <file> has the
extension .script it is chopped when put on the server since sieve
names may not contain a '.'.

.I -a <name>
Set <name> as the active script. The list of available names can be
obtained from the '-l' option..

.I -d <name>
Delete the sieve script on the server with <name>.

.I -m <mechanism>
Force installsieve to use <mechanism> for authentication. If not
specified the strongest authentication mechanism is chosen.

.I -g <name>
Get the sieve script with <name> and save it to disk with a ".script"
extension. If a file with that name already exists it is
overwritten.

.I -u <user>
Userid/Authname to use for authentication; by default, the current user.
