.\" -*- nroff -*-
.TH KRB.EQUIV 5
.\" Copyright 1998 Carnegie Mellon University
.\" 
.\" No warranties, either expressed or implied, are made regarding the
.\" operation, use, or results of the software.
.\"
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation is hereby granted for non-commercial purposes only
.\" provided that this copyright notice appears in all copies and in
.\" supporting documentation.
.\"
.\" Permission is also granted to Internet Service Providers and others
.\" entities to use the software for internal purposes.
.\"
.\" The distribution, modification or sale of a product which uses or is
.\" based on the software, in whole or in part, for commercial purposes or
.\" benefits requires specific, additional permission from:
.\"
.\"  Office of Technology Transfer
.\"  Carnegie Mellon University
.\"  5000 Forbes Avenue
.\"  Pittsburgh, PA  15213-3890
.\"  (412) 268-4387, fax: (412) 268-7395
.\"  tech-transfer@andrew.cmu.edu
.SH NAME
\fB/etc/krb.equiv\fR \- Kerberos equivalences
.SH DESCRIPTION
.I krb.equiv
contains zero or more lines, each of which describes a mapping of a kerberos
principal (\fIuserid@host\fR) to a local user (\fIuserid\fR or alias).  
Each line of the file consists of two fields,
separated by at least one whitespace character; other blanks are
ignored.  The first field is the kerberos principal name to
remap, and the second is the name of the corresponding local user.
.SH SAMPLE FILE
.PP
.nf
tyq4@ANDY.CMU.EDU tyq4
tyq4@DEANNA.ORG tyq4
ty347@ECE.CMU.EDU tyq4
jj12@ANDY.CMU.EDU tick
tick@DEANNA.ORG tick
jy9o@ANDY.CMU.EDU jyager
jyager@CS.CMU.EDU jyager

