.\" -*- nroff -*-
.TH POP3D 8
.\" Copyright 1996, Carnegie Mellon University.  All Rights Reserved.
.\" 
.\" This software is made available for academic and research
.\" purposes only.  No commercial license is hereby granted.
.\" Copying and other reproduction is authorized only for research,
.\" education, and other non-commercial purposes.  No warranties,
.\" either expressed or implied, are made regarding the operation,
.\" use, or results of the software.  Such a release does not permit
.\" use of the code for commercial purposes or benefits by anyone
.\" without specific, additional permission by the owner of the code.
.SH NAME
pop3d \- POP3 server process
.SH SYNOPSIS
.B pop3d
[
.B \-k
]
.SH DESCRIPTION
.I Pop3d
is a POP3 server.
It accepts commands on its standard input and responds on its standard output.
It is normally invoked by
.IR inetd (8)
with those descriptors attached to a remote client connection.
.PP
.I Pop3d
reads its configuration options out of the
.IR imapd.conf (5)
file.
.PP
If the directory
.RI log/ user
exists under the directory specified in the
.I configdirectory
configuration option, then
.I pop3d
will create protocol telemetry logs for sessions authenticating as
.IR user .
The telemetry logs will be stored in the 
.RI log/ user
directory with a filename of the
.I pop3d
process-id.
.SH OPTIONS
.TP
.B \-k
Serve MIT's KPOP (Kerberized POP) protocol instead.
.SH FILES
.TP
.B /etc/imapd.conf
