.\" -*- nroff -*-
.TH QUOTA 8
.\" Copyright 1998 Carnegie Mellon University
.\" 
.\" No warranties, either expressed or implied, are made regarding the
.\" operation, use, or results of the software.
.\"
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation is hereby granted for non-commercial purposes only
.\" provided that this copyright notice appears in all copies and in
.\" supporting documentation.
.\"
.\" Permission is also granted to Internet Service Providers and others
.\" entities to use the software for internal purposes.
.\"
.\" The distribution, modification or sale of a product which uses or is
.\" based on the software, in whole or in part, for commercial purposes or
.\" benefits requires specific, additional permission from:
.\"
.\"  Office of Technology Transfer
.\"  Carnegie Mellon University
.\"  5000 Forbes Avenue
.\"  Pittsburgh, PA  15213-3890
.\"  (412) 268-4387, fax: (412) 268-7395
.\"  tech-transfer@andrew.cmu.edu
.SH NAME
quota \- report and optionally fix quota usage
.SH SYNOPSIS
.B quota
[
.B \-f
]
[
.IR mailbox-prefix ...
]
.SH DESCRIPTION
.I Quota
generates a report listing quota roots, giving their limits and usage.
If the
.I \-f
option is given, 
.I quota
first fixes any inconsistencies in the quota subsystem, such as
mailboxes with the wrong quota root or quota roots with the wrong
quota usage reported.
If any optional
.I mailbox-prefix
arguments are given, the quota listing (and inconsistency fixing) is
limited to quota roots with names that start with one of the given
prefixes.
.PP
Running
.I quota
with both the 
.I \-f
option and
.I mailbox-prefix
arguments is not recommended.
.PP
.I Quota
reads its configuration options out of the
.IR imapd.conf (5)
file.
.SH OPTIONS
.TP
.B \-f
Fix any inconsistencies in the quota subsystem before generating a
report.
.SH FILES
.TP
.B /etc/imapd.conf
