.\" -*- nroff -*-
.TH RECONSTRUCT 8
.\" 	(C) Copyright 1994 by Carnegie Mellon University
.\" 
.\"                      All Rights Reserved
.\" 
.\" Permission to use, copy, modify, and distribute this software and its 
.\" documentation for any purpose and without fee is hereby granted, 
.\" provided that the above copyright notice appear in all copies and that
.\" both that copyright notice and this permission notice appear in 
.\" supporting documentation, and that the name of CMU not be
.\" used in advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.  
.\" 
.\" CMU DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
.\" ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL
.\" CMU BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR
.\" ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
.\" WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
.\" ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
.\" SOFTWARE.
.SH NAME
reconstruct \- reconstruct mailboxes
.SH SYNOPSIS
.B reconstruct
[
.B \-r
]
.IR mailbox ...
.SH DESCRIPTION
.I Reconstruct
rebuilds one or more IMAP mailboxes.  It can be used to recover from
almost any sort of data corruption.
.PP
If
.I Reconstruct
can find existing header and index files, it attempts to preserve any
data in them that is not derivable from the message files themselves.
The state 
.I reconstruct
attempts to preserve includes the flag names, flag state, and
internaldate.
.I Reconstruct
derives all other information from the message files.
.PP
.I Reconstruct
reads its configuration options out of the
.IR imapd.conf (5)
file.  Any mailbox directory underneath the path specified in the
.I partition-news
configuration option is assumed to be in news format.
.PP
.I Reconstruct does not adjust the quota usage recorded in any quota
root files.  After running
.IR reconstruct ,
it is advisable to run
.IR quota (8)
with the
.I \-f
switch in order to fix the quota root files.
.SH OPTIONS
.TP
.B \-r
Recursively reconstruct all sub-mailboxes of the mailboxes or mailbox
prefixes given as arguments.
.SH FILES
.TP
.B /etc/imapd.conf
