.\" -*- nroff -*-
.TH SYNCNEWS 8
.\" Copyright 1998 Carnegie Mellon University
.\" 
.\" No warranties, either expressed or implied, are made regarding the
.\" operation, use, or results of the software.
.\"
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation is hereby granted for non-commercial purposes only
.\" provided that this copyright notice appears in all copies and in
.\" supporting documentation.
.\"
.\" Permission is also granted to Internet Service Providers and others
.\" entities to use the software for internal purposes.
.\"
.\" The distribution, modification or sale of a product which uses or is
.\" based on the software, in whole or in part, for commercial purposes or
.\" benefits requires specific, additional permission from:
.\"
.\"  Office of Technology Transfer
.\"  Carnegie Mellon University
.\"  5000 Forbes Avenue
.\"  Pittsburgh, PA  15213-3890
.\"  (412) 268-4387, fax: (412) 268-7395
.\"  tech-transfer@andrew.cmu.edu
.SH NAME
syncnews \- synchronize IMAP news mailboxes with active file
.SH SYNOPSIS
.B syncnews
.I active-file
.SH DESCRIPTION
.I Syncnews
compares the list of IMAP news mailboxes with the news active file.
News mailboxes which are not listed in the active file are removed.
Newsgroups listed in the active file but not in the IMAP mailboxes
file have IMAP mailboxes created.
.PP
A newsgroup must have a status of ``y'', ``m'', or ``n'' to be
considered listed in the active file.
.SH FILES
.TP
.B /etc/imapd.conf
.SH BUGS
If a newsgroup is listed in the active file, but does not have the
news spool directories created, 
.I syncnews
will create those news spool directories in the process of creating
the IMAP mailbox.  The created directories are likely to then have
ownership and permissions that do not permit the news server to write
article files.

