/* Automatically generated by compile_st.pl, do not edit */
#ifndef __STRING_TABLE_htmlchar_H_
#define __STRING_TABLE_htmlchar_H_ 1

#include <string.h>

extern int htmlchar_from_string(const char *s);
extern int htmlchar_from_string_len(const char *s, size_t len);

#endif /* __STRING_TABLE_htmlchar_H_ */
