#!perl
use Cassandane::Tiny;

sub test_uidsearch_empty
    :min_version_3_9
{
    my ($self) = @_;
    my $imap = $self->{store}->get_client();

    $imap->create('INBOX.test');
    $self->assert_str_equals('ok', $imap->get_last_completion_response());

    $self->{instance}->run_command({cyrus => 1}, 'squatter');

    my @results;
    my %handlers =
    (
        esearch => sub
        {
            my (undef, $esearch) = @_;
            push(@results, $esearch);
        },
    );

    $imap->select('INBOX.test');
    $imap->_imap_cmd('UID', 0, \%handlers,
        'SEARCH', 'RETURN', '(ALL SAVE COUNT) UID 1:*');
    $self->assert_num_equals(1, scalar @results);
    $self->assert_str_equals('UID', $results[0][1]);
    $self->assert_str_equals('COUNT', $results[0][2]);
    $self->assert_str_equals('0', $results[0][3]);
}
