#!perl
use Cassandane::Tiny;

sub test_https_none
    :want_service_https :needs_component_httpd
{
    my ($self) = @_;

    # skip past setup logs
    $self->{instance}->getsyslog();

    my $https = $self->{instance}->get_service('https');
    my $alpn_map = undef;

    my $response = $self->do_https_request($https, $alpn_map);

    $self->assert_num_equals(1, $response->{success});
    $self->assert_alpn_protocol(undef, undef);
}
