#!perl
use Cassandane::Tiny;

sub test_calendarevent_set_schedulestatus
    :min_version_3_4
    ($self)
{
    my $jmap = $self->default_user->jmap;
    my $default_cal_id = $self->default_user->calendars->default->id;

    my $res = $jmap->CallMethods([
        ['CalendarEvent/set', {
            create => {
                event1 => {
                    calendarIds => {
                        $default_cal_id => JSON::true,
                    },
                    '@type' => 'Event',
                    title => 'test',
                    organizerCalendarAddress => 'mailto:orga@local',
                    participants => {
                        part1 => {
                            '@type' => 'Participant',
                            calendarAddress => 'mailto:part1@local',
                            scheduleStatus => ['2.0', '2.4'],
                        },
                    },
                    start => '2021-01-01T01:00:00',
                    timeZone => 'Europe/Berlin',
                    duration => 'PT1H',
                },
            },
        }, 'R1'],
        ['CalendarEvent/get', {
            ids => ['#event1'],
        }, 'R2'],
    ]);
    $self->assert_deep_equals(['2.0', '2.4'],
        $res->[1][1]{list}[0]{participants}{part1}{scheduleStatus});
}
