#!perl
use Cassandane::Tiny;

sub test_calendarevent_set_privacy_ignore_override
    :min_version_3_7
    ($self)
{
    my $jmap = $self->default_user->jmap;
    my $default_cal_id = $self->default_user->calendars->default->id;

    my $caldav = $self->{caldav};

    xlog "Ignore overriden privacy in CalendarEvent/set";
    my $res = $jmap->CallMethods([
        ['CalendarEvent/set', {
            create => {
                event1 => {
                    calendarIds => {
                        $default_cal_id => JSON::true,
                    },
                    uid => 'event1uidlocal',
                    title => 'event1',
                    start => '2020-01-01T09:00:00',
                    timeZone => 'Europe/Vienna',
                    duration => 'PT1H',
                    privacy => 'private',
                    recurrenceRule => {
                        frequency => 'daily',
                        count => 3,
                    },

                    recurrenceOverrides => {
                        '2020-01-02T09:00:00' => {
                            title => 'event1Override',
                            privacy => 'secret',
                        },
                    },
                },
            },
        }, 'R1'],
    ]);
    my $xhref = $res->[0][1]{created}{event1}{'x-href'};
    $self->assert_not_null($xhref);

    $res = $caldav->Request('GET', $xhref);
    $self->assert($res->{content} =~ m/^CLASS:PRIVATE\r$/mi);
    $self->assert(not $res->{content} =~ m/^CLASS:CONFIDENTIAL\r$/mi);
}
