#!perl
use Cassandane::Tiny;

sub test_calendarevent_get_color_categories
    :min_version_3_7
    ($self)
{
    my ($id, $ical) = $self->icalfile('color-categories');

    my $event = $self->putandget_vevent($id, $ical);
    $self->assert_not_null($event);
    $self->assert_str_equals("red", $event->{color});
    # XXX quirk: the former implementation omitted the color-named
    # keyword. The new implementation preserves it.
    $self->assert_not_null($event->{keywords}{red});
}
