#!perl
use Cassandane::Tiny;

sub test_calendarevent_get_organizer
    :min_version_3_4
    ($self)
{
    my ($id, $ical) = $self->icalfile('organizer');

    my $event = $self->putandget_vevent($id, $ical);
    my $wantParticipants = hashbag(
        ignore() => {
            '@type' => 'Participant',
            name => 'Organizer',
            roles => {
                'owner' => JSON::true,
            },
            calendarAddress => 'mailto:organizer@local',
        },
        ignore() => {
            '@type' => 'Participant',
            calendarAddress => 'mailto:attendee@local',
        },
    );
    $self->assert_cmp_deeply($wantParticipants, $event->{participants});
    $self->assert_equals('mailto:organizer@local', $event->{organizerCalendarAddress});
}
