#!perl
use Cassandane::Tiny;

sub test_calendarevent_get_endtimezone
    :min_version_3_1
    ($self)
{
    my ($id, $ical) = $self->icalfile('endtimezone');

    my $event = $self->putandget_vevent($id, $ical);
    $self->assert_not_null($event);
    $self->assert_str_equals("2016-09-28T13:00:00", $event->{start});
    $self->assert_str_equals("Europe/London", $event->{timeZone});
    $self->assert_str_equals("Europe/Vienna", $event->{endTimeZone});
    $self->assert_str_equals("PT1H", $event->{duration});
}
