#!perl
use Cassandane::Tiny;

sub test_calendarevent_set_locations
    :min_version_3_1
    ($self)
{
    my $jmap = $self->default_user->jmap;
    my $default_cal_id = $self->default_user->calendars->default->id;

    my $calid = $self->default_user->calendars->default->id;

    my $locations = {
        # A couple of sparse locations
        locA => {
            name => "location A",
        },
        locB => {
            name => "location B",
        },
        locC => {
            coordinates => "geo:48.208304,16.371602",
            name => "a place in Vienna",
        },
        locD => {
            coordinates => "geo:48.208304,16.371602",
        },
        locE => {
            name => "location E",
            links => {
                link1 => {
                    href => 'https://foo.local',
                    rel => "enclosure",
                },
                link2 => {
                    href => 'https://bar.local',
                    rel => "enclosure",
                },
            },
        },
        # A full-blown location
        locG => {
            name => "location G",
            coordinates => "geo:48.2010,16.3695,183",
        },
        # A location with name that needs escaping
        locH => {
            name => "location H,\nhas funny chars.",
        },
    };
    my $virtualLocations = {
        locF => {
            name => "location F",
            uri => "https://somewhere.local",
        },
    };

    my $event =  {
        calendarIds => {
            $calid => JSON::true,
        },
        "title"=> "title",
        "description"=> "description",
        "start"=> "2015-11-07T09:00:00",
        "duration"=> "PT1H",
        "timeZone" => "Europe/London",
        "showWithoutTime"=> JSON::false,
        "freeBusyStatus"=> "free",
        "locations" => $locations,
        "virtualLocations" => $virtualLocations,
    };

    my $ret = $self->createandget_event($event);
    $event->{id} = $ret->{id};
    $event->{calendarIds} = $ret->{calendarIds};
    $self->assert_normalized_event_equals($event, $ret);
}
