#!perl
use Cassandane::Tiny;

sub test_calendarprincipal_querychanges
    :min_version_3_3 :needs_component_jmap
{
    my ($self) = @_;
    my $jmap = $self->{jmap};

    my $res = $jmap->CallMethods([
        ['Principal/queryChanges', {
            sinceQueryState => 'whatever',
        }, 'R1']
    ]);
    $self->assert_str_equals('cannotCalculateChanges', $res->[0][1]{type});
}
