#!perl
use Cassandane::Tiny;

sub test_session_capability_isrfc
    :min_version_3_5
    ($self)
{
    my $jmap = $self->{jmap};

    my $session = $jmap->get_client_session->client_session;
    $self->assert_not_null($session);

    $self->assert_deep_equals(
        $session->{capabilities}{'https://cyrusimap.org/ns/jmap/calendars'},
        { isRFC => JSON::true });
}
