/* jmap_data_types.c -- JMAP Data Types table */
/* SPDX-License-Identifier: BSD-3-Clause-CMU */
/* See COPYING file at the root of the distribution for more details. */

/* The lookup table and iterator for JMAP data types live here, in the base
 * library, rather than in jmap_api.c (which is only linked into the http
 * daemon).  mboxevent.c -- which is in the base library and runs in every
 * daemon -- needs the table to build its vnd.fastmail.jmapStates parameter.
 * The actual table is generated by gperf into jmap_data_types.h.
 * -- claude, 2026-06-03 */

#include <config.h>

#include <stddef.h>

#include "imap/jmap_data_types.h"
