# $Id: Makefile.dist,v 1.11 2010/01/06 17:01:30 murch Exp $
# it would be nice to figure out how to make "Makefile" do an
# 'include' of this file.
# we'd have to make this use srcdir and only define COMPILE_ET if it wasn't
# already defined.

SNMPGEN = ../snmp/snmpgen

BUILT_SOURCES = lmtpstats.c lmtpstats.h \
	pushstats.c pushstats.h

dist: $(BUILT_SOURCES)

pushstats.c pushstats.h: pushstats.snmp
	$(SNMPGEN) pushstats.snmp

lmtpstats.c lmtpstats.h: lmtpstats.snmp
	$(SNMPGEN) lmtpstats.snmp
