/* prometheus.h -- Aggregate statistics for prometheus
 *
 * Copyright (c) 1994-2017 Carnegie Mellon University.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. The name "Carnegie Mellon University" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For permission or any legal
 *    details, please contact
 *      Carnegie Mellon University
 *      Center for Technology Transfer and Enterprise Creation
 *      4615 Forbes Avenue
 *      Suite 302
 *      Pittsburgh, PA  15213
 *      (412) 268-7393, fax: (412) 268-7395
 *      innovation@andrew.cmu.edu
 *
 * 4. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by Computing Services
 *     at Carnegie Mellon University (http://www.cmu.edu/computing/)."
 *
 * CARNEGIE MELLON UNIVERSITY DISCLAIMS ALL WARRANTIES WITH REGARD TO
 * THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS, IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE
 * FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
 * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include <config.h>
#include <stddef.h>
#include <stdint.h>

#include "lib/mappedfile.h"
#include "lib/util.h"

#define FNAME_PROM_REPORT "report.txt"
#define FNAME_PROM_STATS_DIR "/stats"

/* XXX This will probably eventually be generated by a build-time script from
 * XXX some sort of config file, but hard coding it for now until we know
 * XXX what we want from it.
 */
struct prom_stats {
    pid_t pid;
    char  label[128];
    double total_connections;
    double active_connections;
    double authenticate_count;
    double append_count;
    double capability_count;
    double compress_count;
    double check_count;
    double copy_count;
    double create_count;
    double close_count;
    double delete_count;
    double deleteacl_count;
    double dump_count;
    double expunge_count;
    double examine_count;
    double fetch_count;
    double getacl_count;
};
#define PROM_STATS_INITIALIZER {0}

struct prometheus_handle {
    struct mappedfile *mf;
};

extern const char *prometheus_stats_dir(void);

extern struct prometheus_handle *prometheus_register(void);
extern void prometheus_unregister(struct prometheus_handle **handlep);

#define prometheus_increment(handle, metric) \
    prometheus_adjust_at_offset(handle, offsetof(struct prom_stats, metric), 1.0)

#define prometheus_decrement(handle, metric) \
    prometheus_adjust_at_offset(handle, offsetof(struct prom_stats, metric), -1.0)

extern void prometheus_adjust_at_offset(struct prometheus_handle *handle,
                                        size_t offset, double delta);

extern int prometheus_text_report(struct buf *buf, const char **mimetype);
