# rfc822_header.st - string table data for RFC822 headers
#
# Copyright (c) 1994-2010 Carnegie Mellon University.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
#
# 3. The name "Carnegie Mellon University" must not be used to
#    endorse or promote products derived from this software without
#    prior written permission. For permission or any legal
#    details, please contact
#      Carnegie Mellon University
#      Center for Technology Transfer and Enterprise Creation
#      4615 Forbes Avenue
#      Suite 302
#      Pittsburgh, PA  15213
#      (412) 268-7393, fax: (412) 268-7395
#      innovation@andrew.cmu.edu
#
# 4. Redistributions of any form whatsoever must retain the following
#    acknowledgment:
#    "This product includes software developed by Computing Services
#     at Carnegie Mellon University (http://www.cmu.edu/computing/)."
#
# CARNEGIE MELLON UNIVERSITY DISCLAIMS ALL WARRANTIES WITH REGARD TO
# THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS, IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE
# FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
# AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

%ignore-case
table rfc822_header
ent RFC822_BAD
ent RFC822_UNKNOWN
ent RFC822_BCC "Bcc"
ent RFC822_CC "Cc"
ent RFC822_CONTENT_DESCRIPTION "Content-Description"
ent RFC822_CONTENT_DISPOSITION "Content-Disposition"
ent RFC822_CONTENT_ID "Content-Id"
ent RFC822_CONTENT_LANGUAGE "Content-Language"
ent RFC822_CONTENT_LOCATION "Content-Location"
ent RFC822_CONTENT_MD5 "Content-MD5"
ent RFC822_CONTENT_TRANSFER_ENCODING "Content-Transfer-Encoding"
ent RFC822_CONTENT_TYPE "Content-Type"
ent RFC822_DATE "Date"
ent RFC822_FROM "From"
ent RFC822_IN_REPLY_TO "In-Reply-To"
ent RFC822_MESSAGE_ID "Message-ID"
ent RFC822_REPLY_TO "Reply-To"
ent RFC822_RECEIVED "Received"
ent RFC822_REFERENCES "References"
ent RFC822_SUBJECT "Subject"
ent RFC822_SENDER "Sender"
ent RFC822_TO "To"
ent RFC822_X_DELIVEREDINTERNALDATE "X-Deliveredinternaldate"
ent RFC822_X_ME_MESSAGE_ID "X-ME-Message-ID"

