# rfc822_header.st - string table data for RFC 822 headers
# SPDX-License-Identifier: BSD-3-Clause-CMU
# See COPYING file at the root of the distribution for more details.

%ignore-case
table rfc822_header
ent RFC822_BAD
ent RFC822_UNKNOWN
ent RFC822_BCC "Bcc"
ent RFC822_CC "Cc"
ent RFC822_CONTENT_DESCRIPTION "Content-Description"
ent RFC822_CONTENT_DISPOSITION "Content-Disposition"
ent RFC822_CONTENT_ID "Content-Id"
ent RFC822_CONTENT_LANGUAGE "Content-Language"
ent RFC822_CONTENT_LOCATION "Content-Location"
ent RFC822_CONTENT_MD5 "Content-MD5"
ent RFC822_CONTENT_TRANSFER_ENCODING "Content-Transfer-Encoding"
ent RFC822_CONTENT_TYPE "Content-Type"
ent RFC822_DATE "Date"
ent RFC822_FROM "From"
ent RFC822_IN_REPLY_TO "In-Reply-To"
ent RFC822_MESSAGE_ID "Message-ID"
ent RFC822_REPLY_TO "Reply-To"
ent RFC822_RECEIVED "Received"
ent RFC822_REFERENCES "References"
ent RFC822_SUBJECT "Subject"
ent RFC822_SENDER "Sender"
ent RFC822_TO "To"
ent RFC822_X_DELIVEREDINTERNALDATE "X-Deliveredinternaldate"
ent RFC822_X_ME_MESSAGE_ID "X-ME-Message-ID"

