#!perl
use Cassandane::Tiny;

# maxmessagesize bounds an HTTP/3 request body however it is framed.  With a
# Content-Length over the limit the request is refused when its headers
# arrive; without one, the DATA path has to count, or a client could stream
# an unbounded body into memory.  Either way the answer is 413 and nothing
# is stored, while a body under the limit is still accepted.
sub test_data_maxmessagesize
    :SetMaxMessageSize(8k)
    ($self)
{
    $self->{caldav}->GetCalendars();

    my $ical = sub ($uid, $padlen) {
        my $pad = 'x' x $padlen;
        return <<~"EOF" =~ s/\r?\n/\r\n/gr;
            BEGIN:VCALENDAR
            VERSION:2.0
            PRODID:-//Cassandane//HttpH3//EN
            BEGIN:VEVENT
            UID:$uid
            DTSTAMP:20260101T000000Z
            DTSTART:20260101T100000Z
            DURATION:PT1H
            SUMMARY:maxmessagesize
            DESCRIPTION:$pad
            END:VEVENT
            END:VCALENDAR
            EOF
    };
    my $home = '/dav/calendars/user/cassandane/Default';
    my @ctype = ('Content-Type' => 'text/calendar');

    my %cases = (
        declared => [ @ctype ],
        undeclared => [ @ctype, 'Content-Length' => undef ],
    );
    for my $case (sort keys %cases) {
        my $res = $self->http3_request(
            method => 'PUT',
            path => "$home/$case.ics",
            headers => $cases{$case},
            body => $ical->("h3-$case\@example.com", 40 * 1024),
        );
        $self->assert_num_equals(413, $res->{status});

        my $get = $self->http3_request(path => "$home/$case.ics");
        $self->assert_num_equals(404, $get->{status});
    }

    my $put = $self->http3_request(
        method => 'PUT',
        path => "$home/small.ics",
        headers => [ @ctype, 'Content-Length' => undef ],
        body => $ical->('h3-small@example.com', 1024),
    );
    $self->assert_num_equals(201, $put->{status});
}
