#!perl
use Cassandane::Tiny;

# Store a calendar resource with a PUT and read it back with a GET, both over
# HTTP/3, so a request body and a response body each cross a QUIC stream
sub test_put_get_roundtrip
    ($self)
{
    $self->{caldav}->GetCalendars();

    my $rpath = '/dav/calendars/user/cassandane/Default/roundtrip.ics';
    my $uid = 'h3-roundtrip@example.com';
    my $ical = <<~"EOF" =~ s/\r?\n/\r\n/gr;
        BEGIN:VCALENDAR
        VERSION:2.0
        PRODID:-//Cassandane//HttpH3//EN
        BEGIN:VEVENT
        UID:$uid
        DTSTAMP:20260101T000000Z
        DTSTART:20260101T100000Z
        DURATION:PT1H
        SUMMARY:HTTP/3 round trip
        END:VEVENT
        END:VCALENDAR
        EOF

    my $put = $self->http3_request(
        method => 'PUT',
        path => $rpath,
        headers => [ 'Content-Type' => 'text/calendar; charset=utf-8' ],
        body => $ical,
    );
    $self->assert_num_equals(201, $put->{status});

    my $get = $self->http3_request(method => 'GET', path => $rpath);
    $self->assert_num_equals(200, $get->{status});
    $self->assert_matches(qr/^UID:\Q$uid\E\r$/m, $get->{body});

    my $anon = $self->http3_request(path => $rpath, username => undef);
    $self->assert_num_equals(401, $anon->{status});
}
