#!perl
use Cassandane::Tiny;

sub test_calendaradmin_get
    :min_version_3_8 :AllowCalendarAdmin
    ($self)
{
    my $caldav = $self->{caldav};

    my $res = $caldav->ua->request('GET', $caldav->request_url(""), {
        headers => {
            'Authorization' => $caldav->auth_header(),
        }
    });
    $self->assert_str_equals('200', $res->{status});
}
