#!perl
use Cassandane::Tiny;

sub test_email_query_inmailbox_null
    :min_version_3_1 :needs_component_sieve :Conversations
    ($self)
{
    my $jmap = $self->{jmap};

    xlog $self, "generating email A";
    $self->make_message("Email A") or die;

    xlog $self, "call Email/query with null inMailbox";
    my $res = $jmap->CallMethods([['Email/query', { filter => { inMailbox => undef } }, "R1"]]);
    $self->assert_str_equals("invalidArguments", $res->[0][1]{type});
}
