#!perl
use Cassandane::Tiny;

sub test_badscript_sievec
  : needs_component_sieve {
  my ($self) = @_;

  xlog $self, "Testing sieve script compile failures, via sievec";
  $self->{compile_method} = 'sievec';
  $self->badscript_common();
}
