#!perl
use Cassandane::Tiny;

sub test_ihave_timsieved
{
    my ($self) = @_;

    xlog $self, "Testing sieve ihave (RFC 5463) compile behaviour, via timsieved";
    $self->{compile_method} = 'timsieved';
    $self->ihave_common();
}
