#!perl
use Cassandane::Tiny;

sub test_ihave_sievec
{
    my ($self) = @_;

    xlog $self, "Testing sieve ihave (RFC 5463) compile behaviour, via sievec";
    $self->{compile_method} = 'sievec';
    $self->ihave_common();
}
