#!perl
use Cassandane::Tiny;
use Digest::SHA qw(hmac_sha1_hex);

sub test_forged_empty_key
    :UnixHierarchySep :AltNamespace ($self)
{
    # The victim has an INBOX and a second folder.  The secret we don't want
    # leaked lives in the second folder.
    my $talk = $self->{store}->get_client;
    $talk->create("Archive") or die "create Archive: " . $talk->get_last_error;

    $self->{store}->set_folder("INBOX");
    $self->make_message("Public INBOX message");

    $self->{store}->set_folder("Archive");
    $self->make_message("Secret archived message");

    # Cause the victim's mboxkey.db to be created, but with an entry only for
    # the INBOX -- *not* for the Archive folder we're about to attack.  An
    # mboxkey.db appears in the wild whenever a user has ever issued a
    # GENURLAUTH (or a RESETKEY for a specific mailbox).
    my $seed;
    $talk->_imap_cmd(
        'genurlauth', 0,
        { genurlauth => sub { $seed = $_[1]->[0] } },
        'imap://cassandane@127.0.0.1/INBOX/;uid=1;urlauth=user+cassandane',
        'INTERNAL',
    );
    $self->assert_not_null($seed, 'victim should be able to URLAUTH their own INBOX');

    # Now the attacker forges a token for the *Archive* folder.  Because
    # mboxkey_read() returns {key=NULL, keylen=0} for any mailbox it has never
    # stored, cmd_urlfetch computes HMAC-SHA1 with an empty key -- which is
    # entirely attacker-computable.
    my $attacker = $self->{instance}->create_user('attacker');

    my $rump = 'imap://cassandane@127.0.0.1/Archive/;uid=1;urlauth=user+attacker';
    my $token = '00' . hmac_sha1_hex($rump, '');
    my $forged = "$rump:internal:$token";

    my $stolen;
    $attacker->imap->_imap_cmd(
        'urlfetch', 0,
        { urlfetch => sub { $stolen = $_[1]->[1] } },
        $forged,
    );

    $self->assert_null($stolen);
}
