name: Cyrus IMAP CI Doc Gen

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - 'cyrus-imapd-*'
    paths:
      - 'docsrc/**'
      - 'lib/imapoptions/**'
      - 'cassandane/**/*.pm'
  pull_request:
    branches:
      - master
      - main
      - 'cyrus-imapd-*'
    paths:
      - 'docsrc/**'
      - 'lib/imapoptions/**'
      - 'cassandane/**/*.pm'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/cyrusimap/cyrus-docker:bookworm
        options: --init
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: setup git safe directory
      run: git config --global --add safe.directory /__w/cyrus-imapd/cyrus-imapd
    - name: fetch upstream release tags
      if: ${{ github.repository != 'cyrusimap/cyrus-imapd' }}
      run: |
        git remote add upstream https://github.com/cyrusimap/cyrus-imapd.git
        # n.b. --no-tags does not mean "no tags", it means "no automatic tag
        # following".  we're explicitly fetching the tags we want, we do not
        # need every other tag that's reachable from them
        git fetch --no-tags upstream 'refs/tags/cyrus-imapd-*:refs/tags/cyrus-imapd-*'
    - name: build docs
      env:
        CYRUS_CLONE_ROOT: /__w/cyrus-imapd/cyrus-imapd
      run: cyd makedocs

